version: 2.1

orbs:
  node: circleci/node

jobs:
  eslint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run ESLint
          command: yarn run eslint

workflows:
  leagueMasterCI:
    jobs:
      - eslint